import type { GenerationJobPayload } from "@movprompt/contracts";
import type { QualityDecision } from "@movprompt/creative-engine";
import { COLLECTIONS, hashGenerationConfiguration, newMongoObjectId, type JsonObject, type MongoDatabase } from "@movprompt/db";
import type { RenderLifecycleSnapshot, RenderLifecycleStore } from "./render-lifecycle.js";
import { RenderLifecycleError } from "./render-lifecycle.js";

function directive(decision: QualityDecision): string {
  return [...new Set(decision.failedDimensions)].sort().map((dimension) => `Correct ${dimension.replaceAll("_", " ")} while preserving confirmed campaign facts.`).join(" ");
}

export function createMongoRenderLifecycleStore(database: MongoDatabase): RenderLifecycleStore {
  const runs = database.collection(COLLECTIONS.renderRuns); const attempts = database.collection(COLLECTIONS.renderAttempts); const projects = database.collection(COLLECTIONS.creatorProjects);
  async function owned(runId: string, userId: string) { const run = await runs.findOne({ id: runId, userId }); if (!run) throw new RenderLifecycleError("render_not_found", false); return run; }
  return {
    async load(payload: GenerationJobPayload) {
      const run = await owned(payload.renderRunId, payload.userId); const version = await database.collection(COLLECTIONS.creatorProjectVersions).findOne({ id: run.projectVersionId, userId: payload.userId });
      if (!version) throw new RenderLifecycleError("render_not_found", false);
      if (run.projectId !== payload.projectId || run.projectVersionId !== payload.projectVersionId || run.quoteId !== payload.quoteId || run.capabilityAlias !== payload.capability) throw new RenderLifecycleError("render_job_payload_mismatch", false);
      return { id: String(run.id), userId: String(run.userId), projectId: String(run.projectId), projectVersionId: String(run.projectVersionId), quoteId: String(run.quoteId), capabilityAlias: String(run.capabilityAlias), idempotencyKey: String(run.idempotencyKey), status: run.status, processingStage: run.processingStage, provider: typeof run.provider === "string" ? run.provider : null, providerRequestId: typeof run.providerRequestId === "string" ? run.providerRequestId : null, chargedAt: run.chargedAt instanceof Date ? run.chargedAt : null, refundStatus: run.refundStatus ?? "not_required", qualityAttempt: Number(run.qualityAttempt ?? 0), maxQualityRetries: Number(run.maxQualityRetries ?? 0), qualityRetryDirective: typeof run.qualityRetryDirective === "string" ? run.qualityRetryDirective : null, configuration: (version.configuration ?? {}) as JsonObject } as RenderLifecycleSnapshot;
    },
    async beginProviderSubmission(input) {
      const run = await owned(input.runId, input.userId); if (run.providerRequestId) { if (run.provider !== input.provider) throw new RenderLifecycleError("provider_submission_identity_mismatch", false); return false; }
      if (run.status !== "submitting" || Number(run.qualityAttempt ?? 0) !== input.attemptNumber || (run.provider && run.provider !== input.provider)) throw new RenderLifecycleError("provider_submission_unavailable", false);
      // Exercise the attempt constraint before the billable provider call.
      // A schema/index problem must fail here rather than lose an accepted ID.
      await attempts.updateOne({ renderRunId: input.runId, userId: input.userId, attemptNumber: input.attemptNumber }, { $setOnInsert: { id: newMongoObjectId(), renderRunId: input.runId, userId: input.userId, projectId: run.projectId, projectVersionId: run.projectVersionId, attemptNumber: input.attemptNumber, provider: input.provider, status: "submitting", createdAt: input.now, updatedAt: input.now } }, { upsert: true });
      await runs.updateOne({ id: input.runId, userId: input.userId, status: "submitting" }, { $set: { provider: input.provider, processingStage: "rendering", errorCode: null, errorMessage: null, updatedAt: input.now } }); return true;
    },
    async updateProviderStatus(input) {
      const run = await owned(input.runId, input.userId); await runs.updateOne({ id: input.runId, userId: input.userId }, { $set: { status: input.status, processingStage: input.status === "cancelling" ? "cancelling" : "rendering", errorCode: null, errorMessage: null, updatedAt: input.now } });
      await projects.updateOne({ id: run.projectId, userId: input.userId, currentWorkingVersionId: run.projectVersionId }, { $set: { status: "generating", updatedAt: input.now } });
      await attempts.updateOne({ renderRunId: input.runId, userId: input.userId, attemptNumber: input.attemptNumber }, { $set: { status: input.status === "queued" ? "submitted" : "processing", updatedAt: input.now } });
    },
    async updateProcessingStage(input) { const result = await runs.updateOne({ id: input.runId, userId: input.userId }, { $set: { status: "processing", processingStage: input.stage, errorCode: null, errorMessage: null, updatedAt: input.now } }); if (!result.matchedCount) throw new RenderLifecycleError("render_not_found", false); },
    async recordRetryableFailure(input) { const result = await runs.updateOne({ id: input.runId, userId: input.userId }, { $set: { errorCode: input.errorCode, errorMessage: input.errorMessage, updatedAt: input.now } }); if (!result.matchedCount) throw new RenderLifecycleError("render_not_found", false); },
    async recordProviderTelemetry(input) { if (input.providerCostMicrousd === undefined && input.providerLatencyMs === undefined && input.providerUsage === undefined) return; const result = await attempts.updateOne({ renderRunId: input.runId, userId: input.userId, attemptNumber: input.attemptNumber }, { $set: { ...(input.providerCostMicrousd === undefined ? {} : { providerCostMicrousd: input.providerCostMicrousd }), ...(input.providerLatencyMs === undefined ? {} : { providerLatencyMs: input.providerLatencyMs }), ...(input.providerUsage === undefined ? {} : { providerUsage: input.providerUsage }), updatedAt: input.now } }); if (!result.matchedCount) throw new RenderLifecycleError("render_attempt_not_found", false); },
    async complete(input) {
      await database.transaction(async (session) => { const run = await runs.findOne({ id: input.runId, userId: input.userId }, { session }); if (!run) throw new RenderLifecycleError("render_not_found", false); await runs.updateOne({ id: input.runId, userId: input.userId }, { $set: { status: "completed", processingStage: "ready", outputBucket: input.outputBucket, outputObjectKey: input.outputObjectKey, completedAt: input.now, errorCode: null, errorMessage: null, updatedAt: input.now } }, { session }); await projects.updateOne({ id: run.projectId, userId: input.userId, currentWorkingVersionId: run.projectVersionId }, { $set: { status: "completed", currentAcceptedVersionId: run.projectVersionId, updatedAt: input.now } }, { session }); await attempts.updateOne({ renderRunId: input.runId, userId: input.userId, attemptNumber: input.attemptNumber }, { $set: { status: "accepted", candidateBucket: input.outputBucket, candidateObjectKey: input.outputObjectKey, updatedAt: input.now } }, { session }); });
    },
    async markTerminal(input) {
      await database.transaction(async (session) => { const run = await runs.findOne({ id: input.runId, userId: input.userId }, { session }); if (!run) throw new RenderLifecycleError("render_not_found", false); await runs.updateOne({ id: input.runId, userId: input.userId }, { $set: { status: input.status, processingStage: input.status === "cancelled" ? "cancelled" : "failed", errorCode: input.errorCode, errorMessage: input.errorMessage ?? null, updatedAt: input.now } }, { session }); await projects.updateOne({ id: run.projectId, userId: input.userId, currentWorkingVersionId: run.projectVersionId }, { $set: { status: "failed", updatedAt: input.now } }, { session }); await attempts.updateOne({ renderRunId: input.runId, userId: input.userId, attemptNumber: input.attemptNumber }, { $set: { status: input.status === "cancelled" ? "cancelled" : "failed", updatedAt: input.now } }, { session }); });
    },
    async prepareQualityRetry(input) {
      if (input.decision.status !== "retry" || input.attemptNumber >= input.maxRetries) throw new RenderLifecycleError("quality_retry_unavailable", false); const retryDirective = directive(input.decision);
      await database.transaction(async (session) => { const run = await runs.findOne({ id: input.runId, userId: input.userId }, { session }); if (!run || !run.chargedAt || !run.providerRequestId || run.refundStatus === "refunded") throw new RenderLifecycleError("quality_retry_unavailable", false); const version = await database.collection(COLLECTIONS.creatorProjectVersions).findOne({ id: run.projectVersionId, userId: input.userId }, { session }); if (!version) throw new RenderLifecycleError("render_not_found", false); const report = { status: input.decision.status, score: input.decision.score, failedDimensions: input.decision.failedDimensions, retryDirective }; await attempts.updateOne({ renderRunId: input.runId, userId: input.userId, attemptNumber: input.attemptNumber }, { $set: { status: "quality_rejected", candidateBucket: input.outputBucket, candidateObjectKey: input.outputObjectKey, qualityScore: input.decision.score, qualityDecision: report, updatedAt: input.now } }, { session }); const nextAttempt = input.attemptNumber + 1; await runs.updateOne({ id: input.runId, userId: input.userId }, { $set: { status: "submitting", processingStage: "preparing", provider: null, providerRequestId: null, qualityAttempt: nextAttempt, maxQualityRetries: input.maxRetries, qualityRetryDirective: retryDirective, lastQualityReport: report, errorCode: null, errorMessage: null, updatedAt: input.now } }, { session }); const operationKey = `render.quality_retry:${run.id}:${nextAttempt}`; await database.collection(COLLECTIONS.outboxJobs).updateOne({ topic: "render.start", operationKey }, { $setOnInsert: { id: newMongoObjectId(), topic: "render.start", operationKey, payload: { runId: run.id, userId: run.userId, projectId: run.projectId, projectVersionId: run.projectVersionId, quoteId: run.quoteId, capabilityAlias: run.capabilityAlias, configurationHash: hashGenerationConfiguration(version.configuration), qualityAttempt: nextAttempt }, status: "pending", attempts: 0, maxAttempts: 10, availableAt: input.now, createdAt: input.now, updatedAt: input.now } }, { upsert: true, session }); });
    },
  };
}
