// Kling specialist agent — handles all Kling variants.
// Kling responds best to short, action-driven prompts with bracketed camera tags.

import type { ExpertAgent } from "./registry.ts";

export const klingAgent: ExpertAgent = {
  id: "kling-director",
  displayName: "Kling Specialist",
  matches: (model) => model.startsWith("kling"),

  docSummary: `KLING MODEL DOCUMENTATION (distilled):
- Kling AI is by Kuaishou. Variants: 3.0, 3.0 Omni, 3.0 Omni Edit, 2.6, O1 Video, O1 Video Edit, Motion Control, 3.0 Motion Control.
- Best at: short fluid character motion, expressive faces, dynamic camera moves driven from a single image.
- Reference inputs: image (start frame), optional end frame for transitions, motion-brush masks (Motion Control variants only).
- Audio: NOT generated by Kling — never mention dialogue, SFX, or ambient audio in the prompt.
- Optimal length: 80–180 words. Longer prompts dilute motion fidelity.
- Camera control syntax: bracketed tags like [camera:pan_left], [camera:dolly_in], [camera:crane_up], [camera:zoom_in], [camera:tilt_down], [camera:tracking_right]. Use ONE primary camera tag per prompt.
- Motion Control variants: describe camera as a path of waypoints (start → midpoint → end) and explicitly mark which subjects move vs stay locked.
- Edit variants: describe ONLY the transformation desired, not the full scene re-description.
- Prompt should START with the subject performing an action verb in present tense ("A woman turns...", "The dancer leaps...").`,

  systemAddendum: `═══ TARGET MODEL: KLING (all variants) ═══
- mainPrompt: 80–180 words. START with subject + action verb in present tense.
- Embed exactly ONE primary [camera:*] tag inline. Use snake_case: pan_left, pan_right, dolly_in, dolly_out, crane_up, crane_down, zoom_in, zoom_out, tilt_up, tilt_down, tracking_left, tracking_right, orbit_left, orbit_right.
- Be explicit about motion speed: "gradually", "sudden", "continuous", "slow-burn".
- DO NOT mention audio, dialogue, SFX, or ambient sound — Kling generates silent video.
- For Motion Control variants: describe camera path as 3 waypoints in cameraSuggestions and explicitly tag which subjects are LOCKED vs MOVING.
- For Edit variants: mainPrompt describes ONLY the desired transformation, not the full scene.
- negativePrompt MUST add: "static camera when movement requested, frozen expression, puppet-like motion, abrupt camera cuts".
- Populate cameraTags field with the comma-separated bracketed tags used.
- Populate referenceGuidance field with how the uploaded image acts as the start frame.
- Do NOT populate audioBlock or shotStructure — leave them empty.`,

  examples: `KLING EXAMPLE (single frame, moody portrait in warm light):
mainPrompt: "A woman in a velvet armchair slowly turns her head from the rain-streaked window toward camera, a faint melancholic smile forming as warm tungsten light catches her cheekbones. [camera:dolly_in] gradually tightens from medium to medium close-up. The curtain beside her sways gently in a draft. Rain droplets on the glass behind her dissolve into soft bokeh."
negativePrompt: "morphing, distortion, blurry, watermark, text overlay, frame jumping, flickering, jittering, extra fingers, deformed hands, duplicate subjects, static camera when movement requested, frozen expression, puppet-like motion, abrupt camera cuts"
cameraSuggestions: "Slow [camera:dolly_in], 85mm equivalent, shallow DOF. Hold final frame for 1s of micro-expression."
cameraTags: "[camera:dolly_in]"
referenceGuidance: "Uploaded image is the start frame. Preserve subject identity, clothing texture, and tungsten color cast throughout the clip."
modelNotes: "Kling 3.0 / 2.6 handle subtle facial micro-expressions well. Keep mainPrompt under 180 words for best motion fidelity."
suggestedAspectRatio: "16:9"
suggestedDuration: "5s"`,
};
