import { ClaimDraftRequestSchema, type ClaimDraftRequest } from "@movprompt/contracts";

export const CAMPAIGN_CONTRACT_IDS = {
  draft: "11111111-1111-4111-8111-111111111111",
  project: "22222222-2222-4222-8222-222222222222",
  templateVersion: "33333333-3333-4333-8333-333333333333",
} as const;

/** A complete Template Mode payload shared by boundary tests. */
export function validTemplateClaim(
  overrides: Partial<ClaimDraftRequest> = {},
): ClaimDraftRequest {
  const campaign = {
    promotionKind: "product" as const,
    vertical: "ecommerce" as const,
    goal: "launch" as const,
    presenterMode: "none" as const,
    presenter: { mode: "none" as const },
    market: "KW" as const,
    language: "en" as const,
    arabicDialect: "kuwaiti" as const,
    dialectRegister: "conversational" as const,
    location: "",
    bookingUrl: "",
    whatsapp: "",
    price: "12.500",
    offer: "Free delivery",
    cta: "Shop now",
    brand: "Northfield",
    brandColor: "#d49737",
    aspectRatio: "9:16" as const,
    resolution: "720p" as const,
    subtitles: true,
    audio: true,
  };
  const projectDurationSeconds = 8;
  const scenes = ["hook", "detail", "close"].map((id, index) => ({
    id,
    title: `Scene ${index + 1}`,
    purpose: "Show the confirmed product",
    duration: 2,
    headline: index === 0 ? "Meet Northfield" : "Made for every day",
    voiceover: "Northfield No. 07",
    direction: "Keep the confirmed product label precise and visible.",
    shot: "Hero product shot",
    camera: "Slow push-in",
    lighting: "Soft studio light",
    continuityAnchor: "Northfield No. 07 black bottle",
  }));
  const localizedScenes = scenes.map((scene) => ({
    id: scene.id,
    title: { en: scene.title, ar: scene.title },
    purpose: { en: scene.purpose, ar: scene.purpose },
    duration: scene.duration,
    headline: { en: scene.headline, ar: scene.headline },
    voiceover: { en: scene.voiceover, ar: scene.voiceover },
    direction: scene.direction,
    shot: scene.shot,
    camera: scene.camera,
    lighting: scene.lighting,
    continuityAnchor: scene.continuityAnchor,
  }));
  const source = {
    kind: "product_url" as const,
    subject: "product" as const,
    assetKeys: [],
    facts: [
      { field: "name" as const, value: "Northfield No. 07", provenance: "user_confirmed" as const },
      { field: "description" as const, value: "A confirmed premium fragrance.", provenance: "user_confirmed" as const },
      { field: "brand" as const, value: campaign.brand, provenance: "user_confirmed" as const },
      { field: "price" as const, value: campaign.price, provenance: "user_confirmed" as const },
      { field: "offer" as const, value: campaign.offer, provenance: "manual" as const },
    ],
  };
  const configuration = {
    creatorProject: {
      id: CAMPAIGN_CONTRACT_IDS.project,
      title: "Northfield launch",
      templateId: "luxury-product-reveal",
      status: "ready" as const,
      promotionKind: campaign.promotionKind,
      vertical: campaign.vertical,
      goal: campaign.goal,
      presenterMode: campaign.presenterMode,
      presenter: campaign.presenter,
      location: campaign.location,
      bookingUrl: campaign.bookingUrl,
      whatsapp: campaign.whatsapp,
      product: {
        sourceType: "product_link" as const,
        sourceUrl: "",
        name: "Northfield No. 07",
        description: "A confirmed premium fragrance.",
        price: campaign.price,
        brand: campaign.brand,
        images: [],
      },
      source,
      language: campaign.language,
      arabicDialect: campaign.arabicDialect,
      dialectRegister: campaign.dialectRegister,
      market: campaign.market,
      offer: campaign.offer,
      cta: campaign.cta,
      brandColor: campaign.brandColor,
      logoUrl: "",
      aspectRatio: campaign.aspectRatio,
      resolution: campaign.resolution,
      durationSeconds: projectDurationSeconds,
      subtitles: campaign.subtitles,
      audio: campaign.audio,
      scenes,
      videoUrl: null,
      jobId: null,
      renderRunId: null,
      lastError: null,
      pendingGenerationId: null,
      pendingQuoteCredits: null,
      createdAt: "2026-08-21T00:00:00.000Z",
      updatedAt: "2026-08-21T00:00:00.000Z",
    },
    generation: {
      prompt: "Create a precise premium Kuwait product launch video.",
      durationSeconds: 6,
      aspectRatio: campaign.aspectRatio,
      resolution: campaign.resolution,
      audio: campaign.audio,
      references: [],
      templateQuoteContext: campaign,
      creativeBrief: {
        engineVersion: "gcc-campaign-engine-2026.08",
        templateId: "luxury-product-reveal",
        market: campaign.market,
        language: campaign.language,
        arabicDialect: null,
        dialectRegister: campaign.dialectRegister,
        tone: "premium" as const,
        vertical: campaign.vertical,
        goal: campaign.goal,
        product: {
          name: "Northfield No. 07",
          brand: campaign.brand,
          description: "A confirmed premium fragrance.",
          price: campaign.price,
          offer: campaign.offer,
          callToAction: campaign.cta,
          whatsapp: campaign.whatsapp,
          location: campaign.location,
        },
        scenes: localizedScenes,
        qualityPolicy: {
          tier: "premium" as const,
          acceptanceScore: 85,
          internalRetryLimit: 2,
          hardGates: ["product_identity"],
          scoredDimensions: ["product_identity"],
        },
      },
    },
  };
  return ClaimDraftRequestSchema.parse({
    draftId: CAMPAIGN_CONTRACT_IDS.draft,
    title: "Northfield launch",
    mode: "template",
    templateVersionId: CAMPAIGN_CONTRACT_IDS.templateVersion,
    configuration,
    productRecipe: {
      sourceType: source.kind,
      subject: source.subject,
      name: "Northfield No. 07",
      description: "A confirmed premium fragrance.",
      price: campaign.price,
      brand: campaign.brand,
      images: [],
    },
    campaignRecipe: campaign,
    ...overrides,
  });
}
