import { getTableName } from "drizzle-orm";
import { describe, expect, it } from "vitest";

import {
  accounts,
  auditLogs,
  creatorProjectAssets,
  creatorProjects,
  creatorProjectVersions,
  creditAccounts,
  creditLedger,
  creditReservations,
  entitlements,
  exports,
  generationQuotes,
  notifications,
  paymentBundles,
  paymentEvents,
  paymentOrders,
  renderRuns,
  sessions,
  users,
  verifications,
  videoTemplates,
  videoTemplateVersions,
} from "../src/schema";

describe("portable schema", () => {
  it("uses stable repository-owned table names", () => {
    expect(
      [
        users,
        sessions,
        accounts,
        verifications,
        videoTemplates,
        videoTemplateVersions,
        creatorProjects,
        creatorProjectVersions,
        creatorProjectAssets,
        generationQuotes,
        renderRuns,
        entitlements,
        creditAccounts,
        creditReservations,
        creditLedger,
        exports,
        paymentBundles,
        paymentOrders,
        paymentEvents,
        notifications,
        auditLogs,
      ].map(getTableName),
    ).toEqual([
      "users",
      "sessions",
      "accounts",
      "verifications",
      "video_templates",
      "video_template_versions",
      "creator_projects",
      "creator_project_versions",
      "creator_project_assets",
      "generation_quotes",
      "render_runs",
      "entitlements",
      "credit_accounts",
      "credit_reservations",
      "credit_ledger",
      "exports",
      "payment_bundles",
      "payment_orders",
      "payment_events",
      "notifications",
      "audit_logs",
    ]);
  });
});
